"""
Django settings for minajli project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# ==============================
# المسارات الأساسية
# ==============================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# مفاتيح وتشغيل
# ==============================
# ⚠️ غيّر المفتاح في الإنتاج واستخدم متغيرات بيئية
SECRET_KEY = "django-insecure-z#b&kqflmqbs_4%u3g9i#2c%yyhz!yfrnk=y0k15$2)p3x33(&"
DEBUG = True  # للإنتاج: اجعلها False
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ==============================
# التطبيقات
# ==============================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # خارجي
    "rest_framework",
    "corsheaders",

    # محلي
    "core",
]

# ==============================
# الميدلوير
# ==============================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # يجب أن يكون قبل CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "minajli.urls"

# ==============================
# القوالب (Templates)
# ==============================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # مهم: مجلد القوالب العام بجوار manage.py → minajli/templates/
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,  # يبحث أيضًا داخل templates لكل app
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # لإتاحة STATIC_URL داخل القوالب إن احتجت
                "django.template.context_processors.static",
            ],
        },
    },
]

WSGI_APPLICATION = "minajli.wsgi.application"

# ==============================
# قاعدة البيانات
# ==============================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ==============================
# التحقق من كلمات المرور
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==============================
# الترجمة والتوقيت
# ==============================
LANGUAGE_CODE = "ar"
TIME_ZONE = "Asia/Riyadh"
USE_I18N = True
USE_TZ = True

# ==============================
# CORS / CSRF (للتجربة محليًا)
# ==============================
CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ للتجربة فقط؛ للإنتاج حدّد النطاقات
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# DRF إعداد بسيط (كل شيء مسموح للتجربة)
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

# ==============================
# الملفات الثابتة
# ==============================
STATIC_URL = "static/"
# (اختياري) في التطوير لا تحتاج STATIC_ROOT.
# للإنتاج:
# STATIC_ROOT = BASE_DIR / "staticfiles"

# ==============================
# المفتاح الافتراضي للحقل الأساسي
# ==============================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "home"
